// <auto-generated />
using Kondominium.RepositoryBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Kondominium.RepositoryBase.Migrations
{
    [DbContext(typeof(KondominiumContext))]
    [Migration("20180225232652_Initial5")]
    partial class Initial5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kondominium.Domain.Entities.Apartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BlocoId");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataInsercao");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Numero");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apartamento");
                });

            modelBuilder.Entity("Kondominium.Domain.Entities.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CondominioId");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataInsercao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Bloco");
                });

            modelBuilder.Entity("Kondominium.Domain.Entities.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<int>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataInsercao");

                    b.Property<int>("Estado");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome");

                    b.Property<string>("Rua");

                    b.HasKey("Id");

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("Kondominium.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admininstrador");

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<DateTime>("DataInsercao");

                    b.Property<string>("Email");

                    b.Property<bool>("Excluido");

                    b.Property<bool>("Funcionario");

                    b.Property<bool>("Inquilino");

                    b.Property<string>("Login");

                    b.Property<bool>("Morador");

                    b.Property<bool>("Proprietario");

                    b.Property<bool>("RepresentanteOficial");

                    b.Property<string>("Senha");

                    b.Property<bool>("Sindico");

                    b.Property<string>("Telefone1");

                    b.Property<string>("Telefone2");

                    b.Property<bool>("ViceSindico");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Kondominium.Domain.Entities.Apartamento", b =>
                {
                    b.HasOne("Kondominium.Domain.Entities.Bloco", "Bloco")
                        .WithMany()
                        .HasForeignKey("BlocoId");

                    b.HasOne("Kondominium.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Apartamentos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Kondominium.Domain.Entities.Bloco", b =>
                {
                    b.HasOne("Kondominium.Domain.Entities.Condominio", "Condominio")
                        .WithMany("Blocos")
                        .HasForeignKey("CondominioId");
                });
#pragma warning restore 612, 618
        }
    }
}
